# wrangler.toml update
[triggers]
crons = [
    "0 9,21 * * *",    # 09:00 and 21:00 UTC for game scrapers
    "30 9,21 * * *",   # 09:30 and 21:30 UTC for new games newsletter
    "0 19 * * 5",      # Friday 19:00 UTC for weekly newsletter
    "1 0 * * *"        # 00:01 UTC for cleanup
]